name: Run Sanny Compiler
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'arg'  # This will ignore changes to the specific .arg file in the root of the repository


jobs:
  compile:
    runs-on: windows-latest
 
    env:
      FILENAME: ${{ $env:GITHUB_WORKSPACE\arg }}
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Read arg file content
      id: read_arg_file
      shell: pwsh  # Specify that we want to use PowerShell
      run: |
          $var = Get-Content "$env:GITHUB_WORKSPACE\arg"
          echo "ARG_CONTENT=$($var -join '`n')" >> $GITHUB_ENV  # Join multi-line content with newline


       

    - name: Set up environment and compile
     
      shell: pwsh  # Specify that we want to use PowerShell
      run: |
          & "$env:GITHUB_WORKSPACE\sanny.exe" -c "$env:ARG_CONTENT"
        
    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: my.scm

    - name: Upload compiled.log file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: compile.log

    - name: Delete Previous compile.log
      shell: pwsh
      run: |
        # Use PowerShell command to remove the compile.log file
        if (Test-Path "compile.log") {
          Remove-Item "compile.log"
        }
    - name: Display content of arg file
      run: $Args
