name: Run Sanny Compiler
on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment and compile
      run: |
        # Run sanny.exe from the root of the repository to compile my.txt
        & "$env:GITHUB_WORKSPACE\sanny.exe" --compile "$env:GITHUB_WORKSPACE\my.txt" "$env:GITHUB_WORKSPACE\my2.scm"

    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: my2.scm

      
    - name: Upload compiled.log file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: compile.log

        
    - name: Delete Previous compile.log
      # Use PowerShell as the shell
      run: rm compile.log
