name: Run Sanny Compiler

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Sanny Compiler
      run: |
        # Run sanny.exe with the correct paths using PowerShell syntax
        & "$env:GITHUB_WORKSPACE\sanny.exe" --compile "$env:GITHUB_WORKSPACE\my.txt" "$env:GITHUB_WORKSPACE\my2.scm"
      
    - name: Upload compile.log
      uses: actions/upload-artifact@v3
      with:
        name: my2.scm
        path: $GITHUB_WORKSPACE\my2.scm
