name: Run Sanny Compiler
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'arg'  # This will ignore changes to the specific .arg file in the root of the repository


jobs:
  compile:
    runs-on: windows-latest

    env:
      FILENAME: ${{ secrets.FILE_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment and compile
      run: |
        # Run sanny.exe from the root of the repository to compile my.txt
        & "$env:GITHUB_WORKSPACE\sanny.exe" --compile ${{ env.FILENAME }}

    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: my.scm

    - name: Upload compiled.log file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: compile.log

    - name: Delete Previous compile.log
      shell: pwsh
      run: |
        # Use PowerShell command to remove the compile.log file
        if (Test-Path "compile.log") {
          Remove-Item "compile.log"
        }
