name: Run Sanny Compiler
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'arg'  # This will ignore changes to the specific .arg file in the root of the repository


jobs:
  compile:
    runs-on: windows-latest
 
    env:
      FILENAME: ${{ secrets.FILE_NAME }}
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Read argument file
      id: read_arg
      run: |
        # Read the content of the arg file and store it in Args
        $Args = Get-Content "$env:GITHUB_WORKSPACE\arg" -Raw
        echo "Args=$Args" >> $GITHUB_ENV  # Store in GITHUB_ENV for use in later steps
        echo "Raw Args content: $Args"  # Print for debugging

    - name: Debug Args
      run: |
        echo "Running sanny.exe with arguments: $env:Args"

    - name: Set up environment and compile
      run: |
        & "$env:GITHUB_WORKSPACE\sanny.exe" $env:Args  # Use the Args variable
        
    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: my.scm

    - name: Upload compiled.log file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: compile.log

    - name: Delete Previous compile.log
      shell: pwsh
      run: |
        # Use PowerShell command to remove the compile.log file
        if (Test-Path "compile.log") {
          Remove-Item "compile.log"
        }
    - name: Display content of arg file
      run: Get-Content "$env:GITHUB_WORKSPACE\arg"
