name: Run Sanny Compiler

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'arg'  # This will ignore changes to the specific .arg file in the root of the repository

jobs:
  compile:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read arg file content
        id: read_arg_file
        shell: pwsh  # Specify that we want to use PowerShell
        run: |
          # Read each line of the arg file into an array
          $argsArray = Get-Content -Path "$env:GITHUB_WORKSPACE\arg"
          # Store the array in an environment variable as a single string
          echo "ARG_CONTENT=$( ($argsArray -join ' ') )" >> $GITHUB_ENV

      - name: Set up environment and compile
        shell: pwsh  # Specify that we want to use PowerShell
        run: |
          # Prepare the arguments for sanny.exe
          $arguments = @()
          foreach ($arg in $env:ARG_CONTENT -split ' ') {
              # Replace $env:GITHUB_WORKSPACE with its value
              $arg = $arg -replace '\$env:GITHUB_WORKSPACE', $env:GITHUB_WORKSPACE
              $arguments += $arg
          }
          # Run sanny.exe with the arguments
          & "$env:GITHUB_WORKSPACE\sanny.exe" @arguments  # Pass as separate arguments

      - name: Upload compiled file
        uses: actions/upload-artifact@v3
        with:
          name: compiled-output
          path: my.scm

      - name: Upload compiled.log file
        uses: actions/upload-artifact@v3
        with:
          name: compiled-log
          path: compile.log

      - name: Delete Previous compile.log
        shell: pwsh
        run: |
          # Use PowerShell command to remove the compile.log file
          if (Test-Path "$env:GITHUB_WORKSPACE\compile.log") {
            Remove-Item "$env:GITHUB_WORKSPACE\compile.log"
          }

      - name: Display content of arg file
        run: |
          Write-Host "Content of ARG_FILE: $env:ARG_CONTENT"
