name: Run Sanny Compiler

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        # Assuming sanny.exe is in the repository and located in a folder like 'tools'
        # Update the path if necessary to the correct location of sanny.exe in your repository
        $env:GITHUB_WORKSPACE\sanny.exe --compile "$env:GITHUB_WORKSPACE\my.txt" "$env:GITHUB_WORKSPACE\my2.scm"

    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: my2.scm
