name: Run Sanny Compiler

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        # Run sanny.exe with the correct paths
        .\tools\sanny.exe --compile "$GITHUB_WORKSPACE\my.txt" "$GITHUB_WORKSPACE\my2.scm"
      
    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: |
          $GITHUB_WORKSPACE\my2.scm
          $GITHUB_WORKSPACE\compile.log  # Add this line to upload the compile.log file
