name: Run Sanny Compiler

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        # Run sanny.exe with the correct paths using PowerShell syntax
        & "$env:GITHUB_WORKSPACE\sanny.exe" --compile "$env:GITHUB_WORKSPACE\my.txt" "$env:GITHUB_WORKSPACE\my2.scm"
      
    - name: Upload compiled files
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: |
          $GITHUB_WORKSPACE\my2.scm
          $GITHUB_WORKSPACE\compile.log  # This will upload the compile.log file as well
