name: Run Sanny Compiler
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'arg'  # This will ignore changes to the specific .arg file in the root of the repository


jobs:
  compile:
    runs-on: windows-latest
 
    env:
      FILENAME: ${{ secrets.FILE_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Read file content
      id: read_arg
      run: |
        $FILE_CONTENT = Get-Content "$env:GITHUB_WORKSPACE\arg" -Raw
        echo "file_content=$FILE_CONTENT" >> $GITHUB_ENV  # Set as environment variable

    - name: Set up environment and compile
      run: |
        # Run sanny.exe with the file content
        & "$env:GITHUB_WORKSPACE\sanny.exe" $env:file_content  # Use the environment variable


    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: my.scm

    - name: Upload compiled.log file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: compile.log

    - name: Delete Previous compile.log
      shell: pwsh
      run: |
        # Use PowerShell command to remove the compile.log file
        if (Test-Path "compile.log") {
          Remove-Item "compile.log"
        }
