name: Run Sanny Compiler

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Sanny Compiler
      id: run_sanny
      run: |
        # Run sanny.exe with the correct paths using PowerShell syntax
        & "$env:GITHUB_WORKSPACE\sanny.exe" --compile "$env:GITHUB_WORKSPACE\my.txt" "$env:GITHUB_WORKSPACE\my2.scm"

    - name: Upload compiled file or log
      if: success() && (steps.run_sanny.outputs.my2_scm_exists == 'true')
      uses: actions/upload-artifact@v3
      with:
        name: compiled-output
        path: $GITHUB_WORKSPACE\my2.scm

    - name: Check for my2.scm and upload compile.log if not found
      if: failure() || (steps.run_sanny.outputs.my2_scm_exists != 'true')
      run: |
        echo "my2.scm not found. Uploading compile.log."
        if [ -f "$GITHUB_WORKSPACE\compile.log" ]; then
          echo "Uploading compile.log"
          echo "::set-output name=log_exists::true"
        else
          echo "No compile.log found."
          echo "::set-output name=log_exists::false"
        fi
      shell: bash

    - name: Upload compile.log
      uses: actions/upload-artifact@v3
      with:
        name: compile-log
        path: $GITHUB_WORKSPACE\compile.log
